version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  rust:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Rocket сам возьмёт ROCKET_DATABASES, но если хотите – можно передать переменную
      ROCKET_DATABASES: '{postgres={url="postgres://postgres:postgres@db:5432/postgres"}}'
    volumes:
      - ./uploads:/app/uploads   # хранилище PDF
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - rust
    restart: unless-stopped

volumes:
  pgdata: