FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование скрипта генерации
COPY generate_charts.py .

# Создание директории для графиков
RUN mkdir -p /app/static/charts

CMD ["python", "generate_charts.py"]

