version: "3.9"
services:

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER:  app
      POSTGRES_PASSWORD: app
      POSTGRES_DB:      app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 3s
      retries: 10

  apache:
    build: ./app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
    volumes:
      - ./app/static/uploads:/app/static/uploads
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/var/www
    depends_on:
      - apache

volumes:
  pgdata: