version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  php-apache:
    build: ./php
    volumes:
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    depends_on:
      - postgres
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-apache
    networks:
      - internal

volumes:
  pgdata:

  vendor:

networks:
  internal: