version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: src/php/Dockerfile
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
